### ISSUE TITLE
[BUG] Total tokens not tallied with DSPy and AzureOpenAI client

### ISSUE THREAD

**Issue by arthurgreef** [Arize-ai/phoenix#4730] opened 2024-09-24 17:53 UTC
**Describe the bug**
The total tokens count is not tallied when using Phoenix with DSPy and AzureOpenAI.

**To Reproduce**
1. Run phoenix in python session.
2. Trace any DSPy program that uses the AzureOpenAI client, with Phoenix.
3. Open the Phoenix browser app.
4. Total Tokens is '0'

**Expected behavior**
Expect the total tokens to be tallied from the following completion response.

```json
"created": 1727198954,
  "model": "gpt-4o-2024-08-06",
  "object": "chat.completion",
  "service_tier": null,
  "system_fingerprint": "fp_67802d9a6d",
  "usage": {
    "completion_tokens": 13,
    "prompt_tokens": 609,
    "total_tokens": 622
  },
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - Notebook Runtime N/A
 - Browser Edge
 - Version Latest

**Additional context**

**Comment by axiomofjoy** [comment] 2024-09-28 01:31
Thanks @arthurgreef. This issue is a duplicate of #3119. The recommended workaround is to use our `OpenAIInstrumentor` in conjunction with `DSPyInstrumentor`.

**Closed by axiomofjoy** 2024-09-28 01:31 UTC
Labels: bug, triage
