### ISSUE TITLE
[ENHANCEMENT] Allow for mounting and starting app on subpaths

### ISSUE THREAD

**Issue by Data-drone** [Arize-ai/phoenix#1291] opened 2023-09-10 01:03 UTC
**Is your feature request related to a problem? Please describe.**
If the app is running behind a proxy on a subpath then it seems that js components needed cannot load and are mounted on the root path

**Describe the solution you'd like**
It should be possible to set the `root_path` option in uvicorn and have it successfully mounted on a subpath

**Comment by mikeldking** [comment] 2024-05-13 20:01
duplicate of #2918

**Closed by mikeldking** 2024-05-13 20:01 UTC
Labels: enhancement
