### ISSUE TITLE
Phoenix Docker container start with persistent volume leads to permission denied error (v4.0.3)

### ISSUE THREAD

**Issue by yvokeller** [Arize-ai/phoenix#3187] opened 2024-05-14 08:43 UTC
**Describe the bug**

In the latest release 4.0.3, the Docker container initialisation fails with a permission denied error.

```yaml
services:
  phoenix:
    image: arizephoenix/phoenix:version-4.0.3
    container_name: phoenix
    ports:
      - 6006:6006  # PHOENIX_PORT
      - 4317:4317  # PHOENIX_GRPC_PORT
    networks:
      - aitutor_network
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - phoenix_data:/mnt/data   # PHOENIX_WORKING_DIR

volumes:
  phoenix_data:
```

```
💥 Failed to initialize the working directory at /mnt/data due to an error: [Errno 13] Permission denied: '/mnt/data/exports'.Phoenix requires a working directory to persist data
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/phoenix/env/phoenix/__init__.py", line 7, in <module>
    from .inferences.fixtures import ExampleInferences, load_example
  File "/phoenix/env/phoenix/inferences/fixtures.py", line 12, in <module>
    from phoenix.config import DATASET_DIR
  File "/phoenix/env/phoenix/config.py", line 140, in <module>
    ensure_working_dir()
  File "/phoenix/env/phoenix/config.py", line 129, in ensure_working_dir
    path.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.11/pathlib.py", line 1117, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/data/exports'
```

I then changed to using a direct volume mount and made sure the permissions on the folder are set correctly. That way, Phoenix starts as expected. I expected Phoenix to work fine out of the box with a local driver docker volume, just as for example PostgreSQL can handle it.

```
    volumes:
      - /opt/apps/app/phoenix_data:/mnt/data
```

**To Reproduce**
1. Create compose.yml above
2. Run it using `docker compose up`

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS
 - Docker

**Comment by anticorrelator** [comment] 2024-05-14 16:26
thank you @yvokeller, we recently changed our base Docker image to run as `nonroot`, which can be fiddly in a lot of instances. Thanks for pointing this one out

**Comment by adam-simple** [comment] 2024-05-16 19:29
+1. Using the arizephoenix/phoenix:version-3.24.0 image instead seems to fix it. That's the latest image without the nonroot thing.

**Comment by adam-simple** [comment] 2024-05-17 16:16
Also removing :noroot from the dockerfile and building it on my own fixed it, which is what I'm going with for now

**Comment by mikeldking** [comment] 2024-05-17 16:26
duplicate of #1866 

@adam-simple this is a file group permission issue. If you grant access to the volume mount for the user running the container this should work as intended. We moved to non-root for security asks but we can start publishing a root image.

**Comment by mikeldking** [comment] 2024-05-17 16:26
Closing in favor of #1866

**Closed by mikeldking** 2024-05-17 16:26 UTC
Labels: bug
