### ISSUE TITLE
[BUG] - Prompt Template Parse Variables {{ skip bug

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#4764] opened 2024-09-26 14:28 UTC
There is a bug in the prompt template that doesn't escape the {{ double bracket correctly. The standard industry approach to including braces in templates is to double bracket them. Teams are hitting the issue with their current templates 

https://github.com/Arize-ai/phoenix/blob/e7bfc207ab4e6848572c48341b4b473dbb73ce38/packages/phoenix-evals/src/phoenix/evals/templates.py#L52

Problem Analysis:
Incorrect Variable Extraction: The _parse_variables method in the PromptTemplate class uses a regular expression that doesn't distinguish between escaped and unescaped curly braces. This results in false positive matches where the method identifies variables incorrectly inside the escaped curly braces.

Expected Behavior: You want the format function to replace only the actual variables (like {tool_names}) and not those enclosed in escaped braces (like {{recommendations_tool_name}}).

Standard Python Formatter: The standard Python string.Formatter correctly handles escaped braces, which is why when you use it, the output is as expected.

Solution Approach:
Modify the _parse_variables function to skip over escaped curly braces. Here’s how you could adjust the function:

Skip Escaped Braces: Modify the regular expression to skip over {{ and }} patterns.
Improved Regular Expression:
Update the pattern to ensure it ignores any double braces.
This could be achieved by a negative lookbehind for a single brace before matching.

Example fix:
def _parse_variables(self, text: str) -> List[str]:
    # Pattern to match anything between { and }, ignoring double braces {{ and }}
    pattern = r'(?<!\{)\{' + re.escape(self._start_delim) + "(.*?)" + re.escape(self._end_delim) + r'\}(?!\})'
    variables = re.findall(pattern, text)
    return variables

Explanation:
(?<!\{)\{ ensures that there is no { immediately before the { we are matching, thus skipping double braces.
Similarly, \}(?!\}) ensures there is no } immediately following the } we are matching, which helps in skipping the closing double braces.

**Comment by mikeldking** [comment] 2024-10-01 15:22
duplicate of #4770

**Closed by mikeldking** 2024-10-01 15:22 UTC
Labels: bug, triage
