### ISSUE TITLE
[BUG] Object of type GenerateContentResponse is not JSON serializable

### ISSUE THREAD

**Issue by sandangel** [Arize-ai/phoenix#2424] opened 2024-03-03 13:55 UTC
**Describe the bug**
Get the above error after instrumenting the DSPy program.

<img width="1582" alt="image" src="https://github.com/Arize-ai/phoenix/assets/22189661/41b99ca9-5129-4c8a-b3fc-0dc384c51631">

<img width="1579" alt="image" src="https://github.com/Arize-ai/phoenix/assets/22189661/d29c746e-73e2-49e5-b0a7-d59610cafacf">

The LLM seems to return the correct answer format. If I remove the Phoenix instrument then the program work again.

**To Reproduce**

Install ollama and pull any chat model. I'm using Qwen 1.5 in the script below but feel free to change to others.
Follow phoenix document for DSPy integration.
Save this script to main.py and then run `python main.py 'helo'` 

```python
import asyncio
import os
import sys

import pyperclip
import dspy

from openinference.instrumentation.dspy import DSPyInstrumentor
from opentelemetry import trace as trace_api
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace.export import SimpleSpanProcessor

endpoint = "http://localhost:6006/v1/traces"
resource = Resource(attributes={})
tracer_provider = trace_sdk.TracerProvider(resource=resource)
span_otlp_exporter = OTLPSpanExporter(endpoint=endpoint)
tracer_provider.add_span_processor(SimpleSpanProcessor(span_exporter=span_otlp_exporter))

trace_api.set_tracer_provider(tracer_provider=tracer_provider)
DSPyInstrumentor().instrument()

MODEL = "qwen:14b-chat-v1.5-q4_K_M"

qwen = dspy.OllamaLocal(model=MODEL, temperature=0.7)
input_string = sys.argv[1]


class RephraseText(dspy.Signature):
    """Rephrase text with enhanced clarity, wordings, correct spelling, grammar, and sounds professional"""

    text = dspy.InputField()
    rephrased_text = dspy.OutputField()


rephrase_text = dspy.ChainOfThought(RephraseText)


async def run_ollama() -> str:
    try:
        with dspy.context(lm=qwen):
            response = rephrase_text(text=input_string)
            return response.rephrased_text.strip()
    except Exception as e:
        print(e)
        return ""

async def main() -> None:
    responses = await asyncio.gather(
        run_ollama(),
    )

    response = "{}\n------\n{}".format(*responses)
    pyperclip.copy(response)
    print(response)

asyncio.run(main())
```

**Expected behavior**
DSPy program should execute correctly and fix the input given.

**Environment (please complete the following information):**
 - OS: MacO 14
 - Version
 
```sh
aiohttp==3.9.3
aiosignal==1.3.1
alembic==1.13.1
annotated-types==0.6.0
anyio==4.3.0
arize-phoenix==3.4.1
attrs==23.2.0
backoff==2.2.1
cachetools==5.3.3
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
colorlog==6.8.2
cython==0.29.37
datasets==2.14.7
ddsketch==2.0.4
deprecated==1.2.14
dill==0.3.7
distro==1.9.0
dspy-ai==2.3.6
filelock==3.13.1
frozenlist==1.4.1
fsspec==2023.10.0
google-ai-generativelanguage==0.4.0
google-api-core==2.17.1
google-auth==2.28.1
google-generativeai==0.4.0
googleapis-common-protos==1.62.0
graphql-core==3.2.3
grpcio==1.62.0
grpcio-status==1.62.0
h11==0.14.0
hdbscan==0.8.33
httpcore==1.0.4
httpx==0.25.2
huggingface-hub==0.21.3
idna==3.6
importlib-metadata==6.11.0
jinja2==3.1.3
joblib==1.3.2
llvmlite==0.42.0
mako==1.3.2
markupsafe==2.1.5
mlx==0.5.0
mlx-lm==0.0.13
multidict==6.0.5
multiprocess==0.70.15
mypy==1.8.0
mypy-extensions==1.0.0
numba==0.59.0
numpy==1.26.4
ollama==0.1.7
openai==1.13.3
openinference-instrumentation-dspy==0.1.1
openinference-instrumentation-langchain==0.1.11
openinference-instrumentation-llama-index==1.1.0
openinference-instrumentation-openai==0.1.3
openinference-semantic-conventions==0.1.4
opentelemetry-api==1.23.0
opentelemetry-exporter-otlp==1.23.0
opentelemetry-exporter-otlp-proto-common==1.23.0
opentelemetry-exporter-otlp-proto-grpc==1.23.0
opentelemetry-exporter-otlp-proto-http==1.23.0
opentelemetry-instrumentation==0.44b0
opentelemetry-proto==1.23.0
opentelemetry-sdk==1.23.0
opentelemetry-semantic-conventions==0.44b0
optuna==3.5.0
packaging==23.2
pandas==2.2.1
proto-plus==1.23.0
protobuf==4.25.3
psutil==5.9.8
pyarrow==15.0.0
pyarrow-hotfix==0.6
pyasn1==0.5.1
pyasn1-modules==0.3.0
pydantic==2.5.0
pydantic-core==2.14.1
pynndescent==0.5.11
pyperclip==1.8.2
python-dateutil==2.9.0.post0
pytz==2024.1
pyyaml==6.0.1
regex==2023.10.3
requests==2.31.0
rsa==4.9
safetensors==0.4.2
scikit-learn==1.2.2
scipy==1.12.0
sentencepiece==0.2.0
setuptools==69.1.1
-e file:///Users/san.nguyen/Documents/shortcutx
six==1.16.0
sniffio==1.3.1
sortedcontainers==2.4.0
sqlalchemy==2.0.27
starlette==0.37.1
strawberry-graphql==0.208.2
threadpoolctl==3.3.0
tokenizers==0.15.2
tqdm==4.66.2
transformers==4.38.2
typing-extensions==4.10.0
tzdata==2024.1
ujson==5.9.0
umap-learn==0.5.5
urllib3==2.2.1
uvicorn==0.27.1
wrapt==1.16.0
xxhash==3.4.1
yarl==1.9.4
zipp==3.17.0
```

**Additional context**
Add any other context about the problem here (e.x. a link to a colab)

**Comment by axiomofjoy** [comment] 2024-03-04 23:46
@sandangel Thanks for reporting! I believe this is a duplicate of https://github.com/Arize-ai/openinference/issues/247, which has been resolved on the latest release of `openinference-instrumentation-dspy`. Closing the issue, but feel free to re-open if issues persist.

**Closed by axiomofjoy** 2024-03-04 23:46 UTC
Labels: bug, triage
