### ISSUE TITLE
[ENHANCEMENT] Groups and Subgroups support

### ISSUE THREAD

**Issue by taoari** [Arize-ai/phoenix#4532] opened 2024-09-05 23:21 UTC
**Is your feature request related to a problem? Please describe.**

In the following examples, I made two OpenAI calls. They will show as separate traces. It would be great if I can programmatically group the two OpenAI calls into single traces, or make one the parent of the other.

Sorry that I am new to Phoenix, this feature might be already supported, but I find nowhere in the documentation to describe this.

```python
import os
os.environ['PHOENIX_PROJECT_NAME'] = 'my-llm-app'

import phoenix as px
from phoenix.trace.openai import OpenAIInstrumentor

# Initialize OpenAI auto-instrumentation
OpenAIInstrumentor().instrument()

import os
from openai import OpenAI

# Initialize an OpenAI client
client = OpenAI(api_key=os.environ['OPENAI_API_KEY'])

## 1.

# Define a conversation with a user message
conversation = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello, can you help me with something?"}
]

# Generate a response from the assistant
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=conversation,
)

# Extract and print the assistant's reply
# The traces will be available in the Phoenix App for the above messsages
assistant_reply = response.choices[0].message.content
print(assistant_reply)

## 2.

conversation.append({"role": "assistant", "content": assistant_reply})
conversation.append({"role": "user", "content": "are you a robot?"})
# Generate a response from the assistant
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=conversation,
)

# Extract and print the assistant's reply
# The traces will be available in the Phoenix App for the above messsages
assistant_reply = response.choices[0].message.content
print(assistant_reply)
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by axiomofjoy** [comment] 2024-09-06 00:57
Hey @taoari 👋 Thanks for filing this issue. I believe this is a duplicate of https://github.com/Arize-ai/phoenix/issues/2619. Closing, please feel free to add details to the linked issue.

**Closed by axiomofjoy** 2024-09-06 00:57 UTC
Labels: enhancement, triage
