### ISSUE TITLE
Deprecate pinecone notebooks

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2650] opened 2024-03-20 16:06 UTC

**Comment by axiomofjoy** [comment] 2024-03-21 16:31
Is this a duplicate of #2665?

**Comment by anticorrelator** [comment] 2024-03-21 18:08
@axiomofjoy #2665 is the associated PR, unless I'm misunderstanding?

**Comment by axiomofjoy** [comment] 2024-03-21 19:32
lol my bad

**Closed** 2024-03-22 14:59 UTC
Labels: enhancement
