### ISSUE TITLE
[BUG] application crashes when opening point details sidebar

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#970] opened 2023-07-24 16:51 UTC
**Describe the bug**
Application crashes when opening point details sidebar.

![Screenshot 2023-07-24 at 9 47 45 AM](https://github.com/Arize-ai/phoenix/assets/15664869/669d47c0-db10-48b8-be10-d3526a83678c)

**To Reproduce**
Run the following, go the embeddings page, select some points, and click on the point details for a query.

```
with open("query.pkl", "rb") as f:
    query_ds = pickle.load(f)

with open("database.pkl", "rb") as f:
    database_ds = pickle.load(f)

session = px.launch_app(primary=query_ds, corpus=database_ds)
```

[Archive.zip](https://github.com/Arize-ai/phoenix/files/12148169/Archive.zip)

**Expected behavior**
I expect the point details to launch without crash.

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime: Jupyter
 - Browser: Chrome
 - Version: latest on `llama-index-tutorial-enhancements` (basically the same state as latest `main`)

**Comment by axiomofjoy** [comment] 2023-07-24 16:59
There's some wonky with my schema, working to figure it out.

**Comment by axiomofjoy** [comment] 2023-07-24 17:05
Still seeing this issue after resolving the schema issue.

**Comment by mikeldking** [comment] 2023-07-24 19:28
This was caused by a cached web build that probably had an old version of a npm package. closing.

**Closed by mikeldking** 2023-07-24 19:28 UTC
Labels: bug
