### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by bharathiprodapt** [Arize-ai/phoenix#4805] opened 2024-09-30 12:54 UTC
I have added traces in the Phoenix and i tend to download it but getting Bad Request Error 400
Below is the error i get :

HTTPError: 400 Client Error: Bad Request for url: https://app.phoenix.arize.com/v1/spans

Please help me on this

**Comment by mikeldking** [comment] 2024-09-30 23:18
@bharathiprodapt thamks for reporting. Will have the hosting team take a look. Cc @exiao @fjcasti1

**Comment by fjcasti1** [comment] 2024-10-14 23:02
Looking into this @bharathiprodapt , we've made improvements such that you can upload/download and operate on datasets and experiments. Our next goal is to unblock you with spans/traces and evaluations. Will get back to you soon

**Comment by fjcasti1** [comment] 2024-10-24 23:59
Hi @bharathiprodapt I have tested this and it works for me, can you confirm that the issue persists? Any additional information would be useful in that case. I'm closing the issue since I can make your code work (at least what I could reproduce), feel free to comment and reopen if the problem persists

**Closed by fjcasti1** 2024-10-24 23:59 UTC
Labels: bug, hosted phoenix, llamatrace
