### ISSUE TITLE
[datasets] dataset name collision error is confusing / hard to parse

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3627] opened 2024-06-23 04:32 UTC
<img width="1316" alt="Screenshot 2024-06-22 at 10 31 18 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/eb49ca60-72aa-4fc5-8575-753c85fc352b">

**Comment by axiomofjoy** [comment] 2024-06-24 16:10
Is https://github.com/Arize-ai/phoenix/issues/3605 a duplicate of this issue?

**Closed** 2024-06-25 23:43 UTC
Labels: bug
