### ISSUE TITLE
Save to disc issues on Windows

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#2168] opened 2024-02-01 17:07 UTC

**Comment by axiomofjoy** [comment] 2024-02-02 22:35
Not able to reproduce this issue on Windows 11 with our LlamaIndex tracing tutorial.

**Comment by axiomofjoy** [comment] 2024-02-02 22:40
I have reproduced an error with some user-sent data.

**Comment by RogerHYang** [comment] 2024-02-07 04:32
same issue here https://github.com/Arize-ai/phoenix/issues/2184

**Comment by RogerHYang** [comment] 2024-02-07 04:34
closing this as duplicate of https://github.com/Arize-ai/phoenix/issues/2184

**Closed by RogerHYang** 2024-02-07 04:34 UTC
Labels: bug
