### ISSUE TITLE
[ENHANCEMENT] Remove warning on token

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#1589] opened 2023-10-07 19:48 UTC
I get this warning constantly, it tells not much and don't think its necessary

WARNING:phoenix.experimental.evals.models.openai:gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.

**Comment by mikeldking** [comment] 2023-10-10 16:44
duplicate of #1586

**Comment by mikeldking** [comment] 2024-05-13 19:55
Closing

**Closed by mikeldking** 2024-05-13 19:55 UTC
Labels: duplicate, enhancement
