### ISSUE TITLE
[traces][llama_index] add prompt + completion support for openai completions api

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#1305] opened 2023-09-13 00:33 UTC

**Comment by axiomofjoy** [comment] 2023-09-13 00:37
Notice we don't record prompt and completion when using the legacy completions API and `text-davinci-003`, for example. Not sure on the priority on this, or how we want this to show up in the UI @mikeldking

**Comment by mikeldking** [comment] 2023-09-15 16:27
duplicate of #1200

**Closed by mikeldking** 2023-09-15 16:27 UTC
