### ISSUE TITLE
Support Python 3.13

### ISSUE THREAD

**Issue by didmar** [Arize-ai/phoenix#4621] opened 2024-09-16 15:19 UTC
Based on the `pyproject.toml`, Python 3.13 is not supported. Could it be added?

**Comment by axiomofjoy** [comment] 2024-09-27 22:33
@didmar 3.13 has it's first official release in early October. We will add!

**Comment by didmar** [comment] 2024-09-29 11:45
Great! FYI I was pointing that out because no other dependencies I use have an upper bound on the Python version, so maybe it is OK to not have a bound at all. Not a big deal anyway :)

**Comment by RogerHYang** [comment] 2024-11-07 20:48
duplicate of https://github.com/Arize-ai/phoenix/issues/5082 (currently blocked)

**Closed by RogerHYang** 2024-11-07 20:48 UTC
Labels: enhancement, triage
