### ISSUE TITLE
[ENHANCEMENT] in-product tutorial for first-time users

### ISSUE THREAD

**Issue by axiomofjoy** [Arize-ai/phoenix#568] opened 2023-04-12 05:45 UTC
**Is your feature request related to a problem? Please describe.**
First-time users have difficulty understanding certain components of the UI.

**Describe the solution you'd like**
"So I think now that I am a little bit more acquainted with it and that you walked me through the different features, I feel like it's really intuitive. I feel like it doesn't take long to get used to it all, if I spend another hour with it on my own time I would probably feel very comfortable with it. I think the major point of feedback that I would stress is that that the first time that a user uses this it would be really nice to have a guided walkthrough for the user to make it really really easy, like, hey, this is what this is. This is what that is. This is what you're looking at. So on and so forth."

**Describe alternatives you've considered**
Better documentation and video tutorials. Nothing would beat this, though.

**Additional context**
Suggested by Dionny Santiago in a usability study.

**Comment by mikeldking** [comment] 2023-05-08 16:24
duplicate of #495

**Closed as completed** 2023-05-08 16:25 UTC
Labels: duplicate, enhancement
