### ISSUE TITLE
[BUG] Llama Index Tracing Tutorial Fails on Imports

### ISSUE THREAD

**Issue by hakantekgul** [Arize-ai/phoenix#1600] opened 2023-10-11 18:51 UTC
Colab: https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb 

![Screenshot 2023-10-11 at 11 02 53 AM (1)](https://github.com/Arize-ai/phoenix/assets/14350521/2a0e17e0-a616-42d7-a4a3-71b6aeb285dc)

**Comment by mikeldking** [comment] 2023-10-11 19:12
There's maybe a need to restart the runtime?
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.1.1 which is incompatible.
tensorflow 2.13.0 requires numpy<=1.24.3,>=1.22, but you have numpy 1.25.2 which is incompatible.
Successfully installed arize-phoenix-0.0.44 cython-0.29.36 dataclasses-json-0.5.14 ddsketch-2.0.4 graphql-core-3.2.3 h11-0.14.0 hdbscan-0.8.33 jsonpatch-1.33 jsonpointer-2.4 langchain-0.0.312 langsmith-0.0.43 llama-index-0.8.43 llvmlite-0.41.0 marshmallow-3.20.1 mypy-extensions-1.0.0 numba-0.58.0 numpy-1.25.2 openai-0.28.1 pandas-2.1.1 pynndescent-0.5.10 starlette-0.31.1 strawberry-graphql-0.208.2 tiktoken-0.5.1 typing-inspect-0.9.0 tzdata-2023.3 umap-learn-0.5.4 urllib3-1.26.17 uvicorn-0.23.2
WARNING: The following packages were previously imported in this runtime:
  [numpy]
You must restart the runtime in order to use newly installed versions.
```

**Comment by mikeldking** [comment] 2023-10-11 19:19
Part of the problem is that the -qq swallows the prompt to restart the runtime. I'm not sure this is helpful. A part of the issue I don't understand is why

**Comment by axiomofjoy** [comment] 2023-10-11 19:25
Looks like LlamaIndex set a minimum version for `pandas` and `numpy` as part of their latest release.

**Comment by axiomofjoy** [comment] 2023-10-11 19:25
This is forcing an installation of `pandas` and `numpy` versions that are incompatible with some pre-installed packages on Colab.

**Comment by axiomofjoy** [comment] 2023-10-11 19:28
Here's the error on Colab from running `pip install llama-index`

```
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.6.0,>=0.5.7->llama-index)
  Downloading marshmallow-3.20.1-py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 4.1 MB/s eta 0:00:00
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain>=0.0.303->llama-index) (6.0.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from langchain>=0.0.303->llama-index) (3.8.5)
Requirement already satisfied: anyio<4.0 in /usr/local/lib/python3.10/dist-packages (from langchain>=0.0.303->llama-index) (3.7.1)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain>=0.0.303->llama-index) (4.0.3)
Collecting jsonpatch<2.0,>=1.33 (from langchain>=0.0.303->llama-index)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Collecting langsmith<0.1.0,>=0.0.43 (from langchain>=0.0.303->llama-index)
  Downloading langsmith-0.0.43-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 3.8 MB/s eta 0:00:00
Requirement already satisfied: pydantic<3,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain>=0.0.303->llama-index) (1.10.13)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.10/dist-packages (from langchain>=0.0.303->llama-index) (2.31.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.8.1->llama-index) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.8.1->llama-index) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.8.1->llama-index) (2023.6.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.8.1->llama-index) (4.66.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.3->llama-index) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.3->llama-index) (2023.3.post1)
Collecting tzdata>=2022.1 (from pandas<3.0.0,>=2.0.3->llama-index)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 32.0 MB/s eta 0:00:00
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy[asyncio]>=2.0.15->llama-index) (3.0.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.8.0->llama-index)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.303->llama-index) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.303->llama-index) (3.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.303->llama-index) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.303->llama-index) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.303->llama-index) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain>=0.0.303->llama-index) (1.3.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<4.0->langchain>=0.0.303->llama-index) (3.4)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<4.0->langchain>=0.0.303->llama-index) (1.3.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<4.0->langchain>=0.0.303->llama-index) (1.1.3)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0,>=1.33->langchain>=0.0.303->llama-index)
  Downloading jsonpointer-2.4-py2.py3-none-any.whl (7.8 kB)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.10/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json<0.6.0,>=0.5.7->llama-index) (23.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.3->llama-index) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain>=0.0.303->llama-index) (2023.7.22)
Installing collected packages: urllib3, tzdata, numpy, mypy-extensions, marshmallow, jsonpointer, typing-inspect, pandas, jsonpatch, tiktoken, openai, langsmith, dataclasses-json, langchain, llama-index
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.0.6
    Uninstalling urllib3-2.0.6:
      Successfully uninstalled urllib3-2.0.6
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.1.1 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.26.0 which is incompatible.
tensorflow 2.13.0 requires numpy<=1.24.3,>=1.22, but you have numpy 1.26.0 which is incompatible.
Successfully installed dataclasses-json-0.5.14 jsonpatch-1.33 jsonpointer-2.4 langchain-0.0.312 langsmith-0.0.43 llama-index-0.8.43 marshmallow-3.20.1 mypy-extensions-1.0.0 numpy-1.26.0 openai-0.28.1 pandas-2.1.1 tiktoken-0.5.1 typing-inspect-0.9.0 tzdata-2023.3 urllib3-1.26.17
```

**Comment by axiomofjoy** [comment] 2023-10-11 19:33
Here is the commit where a lower bound on the `numpy` and `pandas` dependencies were specified.

**Comment by mikeldking** [comment] 2023-10-11 19:44
the `-qq` in the notebook I believe is suppressing the runtime reset that's required. Without qq it prints the corrective action
<img width="2407" alt="Screenshot 2023-10-11 at 1 42 17 PM" src="https://github.com/Arize-ai/phoenix/assets/5640648/bb322df1-bfc3-40f8-9c79-a26b78a9e10b">

**Comment by axiomofjoy** [comment] 2023-10-11 20:12
Removed quiet flags in https://github.com/Arize-ai/phoenix/pull/1602

**Comment by axiomofjoy** [comment] 2023-10-11 20:21
Closing this issue since the notebook runs successfully after restarting the runtime. I'll follow up with the LlamaIndex team to see if it's possible to relax the version constraints.

**Closed by axiomofjoy** 2023-10-11 20:21 UTC
Labels: bug

**Comment by mikeldking** [comment] 2023-10-11 23:11
resolved https://github.com/run-llama/llama_index/pull/8078
